version: '3'
services:
  java_app:
    container_name: java_app
    image: bga/java_app:1.0.0
    build: .
    ports:
      - "8080:8080"do
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db


  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432
    environment:

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: demo
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}